# Generated by Django 3.0.7 on 2020-07-08 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=50, null=True, verbose_name='log')),
                ('date_event', models.DateField(auto_now=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(8)], verbose_name='password')),
            ],
        ),
    ]
