# Generated by Django 3.0.7 on 2020-06-10 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
